### ISSUE TITLE
Add isp_id to traits

### ISSUE THREAD

**Issue by rudgirello** [maxmind/GeoIP2-java#190]
Please add isp_id to traits returned as part of the response from the DatabaseReader class (both getObjectNode() and the high-level methods). This field may be useful for analysis/reporting and cross-reference with the CSV. There're scenarios where the UI may rely on the data sourced from the CSV with isp_id being the primary key (loosely speaking), while the performance critical code could be using the mmdb. Hence the need for linking records from the two data sources. 

While I appreciate the fact that the output from the DatabaseReader is intended to be deprived of any MaxMind-specific fields, in this case there's a real missing piece from the conceptual perspective. Perhaps, it'd be a good idea to prefix it with a MaxMind-namespace to clearly indicate that it's not a commonly accepted ISP ID, but rather a proprietary field (e.g., maxmind_isp_id).

**Comment by oschwald** [comment]
This data is not present in the MMDB files. In the CSV files, this key is not stable across builds. I would suggest linking based on the actual data of interest or a hash of it rather than using this ID.

I am going to close this as there is nothing that can be done in the Java reader to expose this as the data is not available in the database. If you would like to further discuss adding a stable key across both the CSVs and MMDB files, please reach out to [support@maxmind.com](mailto:support@maxmind.com).
