### ISSUE TITLE
What happen using reader.asn(ipAddress) when the ipaddress has many network prefix in the mmdb file

### ISSUE THREAD

**Issue by LinG955** [maxmind/GeoIP2-java#352]
Hi, team. I store 1million record (prefix,prefix_len,asn,asn_name) in the mmdb file. As I have an  ipAddress, I would like to get the  record who has the max(prefix_len) when using `reader.asn(ipAddress)`. The reader.asn(ipAddress) will return the last record matching one in the mmdb file ? When I test when the data volume is small, it always returns the last record that matche, but in the case of 1 million records, it may not necessarily follow this rule. How can I solve this problem.

- Test data
```
172.72.0.0/14,14,11426,Charter Communications Inc
172.72.128.0/18,18,11426,Test 18
172.72.152.0/26,26,11426,Test 26
172.72.152.0/21,21,11426,Test 21
```

- Test Code
```java
package com.example.test;

import com.maxmind.db.CHMCache;
import com.maxmind.geoip2.DatabaseReader;
import com.maxmind.geoip2.exception.GeoIp2Exception;
import com.maxmind.geoip2.model.AsnResponse;

import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.List;

public class GeneralTest {
    public static void main(String[] args) {
        try {
            long startTime = System.currentTimeMillis();

        
            File database = new File("out.mmdb");
            DatabaseReader reader = new DatabaseReader.Builder(database)
                    .build();
            InetAddress ipAddress = InetAddress.getByName("172.72.152.2");
             
            AsnResponse maxPrefixRecord = reader.asn(ipAddress);

            if (maxPrefixRecord != null) {
                System.out.println("Prefix: " + maxPrefixRecord.getNetwork().toString());
                System.out.println("Prefix Length: " + maxPrefixRecord.getNetwork().getPrefixLength());
                System.out.println("ASN: " + maxPrefixRecord.getAutonomousSystemNumber());
                System.out.println("ASN Name: " + maxPrefixRecord.getAutonomousSystemOrganization());
            } else {
                System.out.println("not found");
            }

            // time
            long endTime = System.currentTimeMillis();

            long total = endTime - startTime;
            System.out.println("Consume time: " + total);

        } catch (IOException | GeoIp2Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by ugexe** [comment]
The MMDB format, by design, doesn't support overlapping network ranges. Given an IP address, there should be only one specific network range that matches it. When you query an IP address that falls within multiple overlapping ranges, the behavior you're observing is probably an unintended side effect due to the overlapping records.

To address this:

* Ensure that your MMDB does not have overlapping network ranges.
* In the case where multiple network ranges are possible for an IP, decide on a method to determine which record to include in your custom MMDB. One method might be to always choose the network with the longest prefix.

**Comment by LinG955** [comment]
Thanks for your answer!! Ensuring that network segments do not overlap is not an easy task. I give an example:
- IP1 has two network range, namely network range 1 and network range 2. 
- Assuming that network range 1 has the longest prefix. Considering only IP1, we can naturally exclude network range 2 when generating the mmdb file. 
- But IP2 will be in network range 2. It will lack of network range, if exclude network range 2 when generating the mmdb file. 
We have thousands of IPs. How should we solve this situation? looking forward to your suggestion

**Comment by LinG955** [comment]
> 
Thanks for your answer!! Ensuring that network segments do not overlap is not an easy task. I give an example:
- IP1 has two network range, namely network range 1 and network range 2. 
- Assuming that network range 1 has the longest prefix. Considering only IP1, we can naturally exclude network range 2 when generating the mmdb file. 
- But IP2 will be in network range 2. It will lack of network range, if exclude network range 2 when generating the mmdb file. 
We have thousands of IPs. How should we solve this situation? looking forward to your suggestion

**Comment by oschwald** [comment]
This issue is pretty far removed from the Java reader. The database format only allows one record for any particular record. You will need to build in the appropriate logic when writing your MMDB file. Both the Perl and Go writers provide functionality for merging records that you may want to look at.
